// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using openswaggerNswag.Models;

namespace openswaggerNswag.Migrations
{
    [DbContext(typeof(todocontextContext))]
    partial class todocontextContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("openswaggerNswag.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("openswaggerNswag.Models.Todoitems", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)");

                    b.Property<short>("IsComplete")
                        .HasColumnType("bit(1)");

                    b.Property<string>("Name")
                        .IsUnicode(false);

                    b.Property<string>("Rating");

                    b.HasKey("Id");

                    b.ToTable("todoitems","todocontext");
                });
#pragma warning restore 612, 618
        }
    }
}
